/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "System/System.h"

int main(void)
{
  /* 1. Hardware Initialization */
  System_setup();

  /* 2. OS Initialization and start running tasks */
  RTOS_setup();

  /* 3. Should never be reached unless scheduler fails */
  for (;;);
}
