# -*- coding: utf-8 -*-
"""Distance_by_video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17k6j-KADApv0zkG5kwjfnlMEhbh4VGy3
"""

from google.colab import files
import cv2
from ultralytics import YOLO
import easyocr
import re
import math

print("="*60)
print("🚗 LICENSE PLATE READER - WITH DISTANCE MEASUREMENT")
print("="*60)

# 1. رفع الفيديو
print("\n📤 Upload your video:")
uploaded = files.upload()
video_path = list(uploaded.keys())[0]

# 2. فتح الفيديو
cap = cv2.VideoCapture(video_path)

# 3. معلومات الفيديو
fps = int(cap.get(cv2.CAP_PROP_FPS))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

# 4. فيديو الناتج
output_path = '/content/output_with_distance.mp4'
out = cv2.VideoWriter(output_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (width, height))

# 5. تحميل النماذج
car_detector = YOLO('yolov8n.pt')
reader = easyocr.Reader(['en'], gpu=False, verbose=False)

# 6. متغيرات
frame_count = 0
detected_plates = {}  # dictionary: {plate: {'frame': frame, 'confidence': conf, 'distance': dist}}
MIN_CAR_WIDTH = 150

# ============================================
# 🆕 إعدادات المسافة (حسب كاميرتك)
# ============================================
FOCAL_LENGTH = 700          # الطول البؤري (يحتاج معايرة حسب الكاميرا)
KNOWN_PLATE_WIDTH = 0.45    # عرض اللوحة بالمتر (45 سم)
KNOWN_PLATE_HEIGHT = 0.15   # ارتفاع اللوحة بالمتر (15 سم)

# الألوان
GREEN = (0, 255, 0)
RED = (0, 0, 255)
YELLOW = (0, 255, 255)
WHITE = (255, 255, 255)
BLUE = (255, 0, 0)
CYAN = (255, 255, 0)

# ============================================
# 🆕 دالة حساب المسافة
# ============================================
def calculate_distance(plate_width_px, focal_length=FOCAL_LENGTH, known_width=KNOWN_PLATE_WIDTH):
    """
    حساب المسافة بين الكاميرا واللوحة
    المعادلة: المسافة = (العرض الحقيقي * الطول البؤري) / العرض بالبكسل
    """
    if plate_width_px > 0:
        distance = (known_width * focal_length) / plate_width_px
        return distance
    return float('inf')

print(f"\n🎥 Processing {total_frames} frames...")
print("📏 Distance measurement enabled")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    frame_count += 1

    # كل 10 إطارات
    if frame_count % 10 == 0:
        results = car_detector(frame, verbose=False)

        for box in results[0].boxes:
            if int(box.cls[0]) == 2 and float(box.conf[0]) > 0.5:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                car_width = x2 - x1

                # العربية قريبة؟
                if car_width > MIN_CAR_WIDTH:

                    # منطقة اللوحة
                    plate_y1 = int(y2 - (y2 - y1) * 0.3)
                    plate_region = frame[plate_y1:y2, x1:x2]

                    if plate_region.size > 0:
                        # تحسين الصورة للقراءة
                        gray = cv2.cvtColor(plate_region, cv2.COLOR_BGR2GRAY)
                        gray = cv2.equalizeHist(gray)
                        _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

                        # قراءة اللوحة
                        result = reader.readtext(thresh, detail=0, paragraph=True)
                        if result:
                            # تنظيف النص
                            cleaned = re.sub(r'[^A-Z0-9]', '', result[0].upper().replace(' ', ''))

                            if len(cleaned) >= 4:
                                # تقدير نسبة الثقة
                                confidence = min(95, 60 + len(cleaned) * 5)

                                # 🆕 حساب عرض اللوحة بالبكسل
                                plate_width_px = x2 - x1

                                # 🆕 حساب المسافة
                                distance = calculate_distance(plate_width_px)

                                # عرض المسافة بالمتر
                                distance_text = f"{distance:.2f}m" if distance != float('inf') else "Unknown"

                                # تخزين اللوحة مع التفاصيل (بما فيها المسافة)
                                if cleaned not in detected_plates:
                                    detected_plates[cleaned] = {
                                        'frame': frame_count,
                                        'confidence': confidence,
                                        'distance': distance  # 🆕 تخزين المسافة
                                    }
                                    print(f"\n✅ NEW PLATE at frame {frame_count}: {cleaned}")
                                    print(f"   🎯 Confidence: {confidence:.0f}%")
                                    print(f"   📏 Distance: {distance_text}")

                                # ============================================
                                # 🎨 رسم المربعات والكتابة (مع إضافة المسافة)
                                # ============================================

                                # 1. مربع العربية (أخضر)
                                cv2.rectangle(frame, (x1, y1), (x2, y2), GREEN, 3)

                                # 2. مربع اللوحة (أحمر)
                                cv2.rectangle(frame, (x1, plate_y1), (x2, y2), RED, 3)

                                # 3. خلفية للنص
                                text = cleaned
                                font = cv2.FONT_HERSHEY_SIMPLEX
                                font_scale = 0.7
                                thickness = 2
                                (text_w, text_h), _ = cv2.getTextSize(text, font, font_scale, thickness)

                                # خلفية سوداء للكتابة
                                cv2.rectangle(frame, (x1, y1 - text_h - 50), (x1 + text_w + 200, y1), (0, 0, 0), -1)

                                # 4. كتابة رقم اللوحة (أصفر)
                                cv2.putText(frame, f"Plate: {text}", (x1 + 5, y1 - 10),
                                           font, font_scale, YELLOW, thickness)

                                # 5. كتابة نسبة الثقة (أزرق فاتح)
                                cv2.putText(frame, f"Conf: {confidence:.0f}%", (x1 + 5, y1 - 35),
                                           font, 0.6, CYAN, 2)

                                # 🆕 6. كتابة المسافة (أبيض)
                                cv2.putText(frame, f"Dist: {distance_text}", (x1 + 5, y1 - 58),
                                           font, 0.6, WHITE, 2)

                                # 7. كتابة عرض العربية (رمادي)
                                cv2.putText(frame, f"Width: {car_width}px", (x1, y2 + 25),
                                           font, 0.4, WHITE, 1)

    # حفظ الإطار
    out.write(frame)

cap.release()
out.release()

print("\n" + "="*60)
print("📊 FINAL RESULTS (WITH DISTANCE)")
print("="*60)
print("   🚗 Plate - Frame - Confidence - Distance")
print("-"*60)

for plate, info in detected_plates.items():
    distance = info.get('distance', float('inf'))
    dist_str = f"{distance:.2f}m" if distance != float('inf') else "Unknown"
    print(f"   🚗 {plate} - frame {info['frame']} (Confidence: {info['confidence']:.0f}%) - Distance: {dist_str}")

print(f"\n📊 Statistics:")
print(f"   Total plates detected: {len(detected_plates)}")

print(f"\n🎥 Video saved to: {output_path}")

# تحميل الفيديو
files.download(output_path)

# ============================================
# 🆕 تصدير النتائج إلى ملف CSV
# ============================================
import csv

csv_path = '/content/plate_detections_with_distance.csv'
with open(csv_path, 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['Plate', 'Frame', 'Confidence (%)', 'Distance (m)'])

    for plate, info in detected_plates.items():
        distance = info.get('distance', float('inf'))
        dist_str = f"{distance:.2f}" if distance != float('inf') else "Unknown"
        writer.writerow([plate, info['frame'], f"{info['confidence']:.0f}", dist_str])

print(f"📊 Results exported to: {csv_path}")
files.download(csv_path)

print("\n✅ Processing complete!")