# -*- coding: utf-8 -*-
"""Distance_by_camera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6fITwfEZ_BHYaJR7Ck1WQYbGIBSToBX
"""

from google.colab import files
import cv2
from ultralytics import YOLO
import easyocr
import re
import math
from IPython.display import display, Javascript, Image
from google.colab.output import eval_js
from base64 import b64decode

print("="*60)
print("🚗 REAL-TIME LICENSE PLATE READER - WITH DISTANCE")
print("="*60)

# ============================================
# إعدادات الكاميرا
# ============================================
FOCAL_LENGTH = 700          # الطول البؤري (يحتاج معايرة حسب الكاميرا)
KNOWN_PLATE_WIDTH = 0.45    # عرض اللوحة بالمتر (45 سم)
MIN_CAR_WIDTH = 150
MIN_CONFIDENCE = 60

# الألوان
GREEN = (0, 255, 0)
RED = (0, 0, 255)
YELLOW = (0, 255, 255)
WHITE = (255, 255, 255)
CYAN = (255, 255, 0)

# ============================================
# تحميل النماذج
# ============================================
print("\n📥 Loading models...")
car_detector = YOLO('yolov8n.pt')
reader = easyocr.Reader(['en'], gpu=False, verbose=False)
print("✅ Models loaded successfully!")

# ============================================
# دوال المساعدة
# ============================================

def calculate_distance(plate_width_px, focal_length=FOCAL_LENGTH, known_width=KNOWN_PLATE_WIDTH):
    if plate_width_px > 0:
        distance = (known_width * focal_length) / plate_width_px
        return distance
    return float('inf')

def preprocess_for_ocr(plate_img):
    gray = cv2.cvtColor(plate_img, cv2.COLOR_BGR2GRAY)
    gray = cv2.equalizeHist(gray)
    _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    return thresh

# ============================================
# دالة قراءة اللوحة من الصورة
# ============================================

def read_plate_from_frame(frame):
    """قراءة اللوحات من الإطار"""
    results = car_detector(frame, verbose=False, conf=0.5)
    plates_found = []

    for box in results[0].boxes:
        if int(box.cls[0]) == 2:  # سيارة
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            car_width = x2 - x1

            if car_width > MIN_CAR_WIDTH:
                # منطقة اللوحة
                plate_y1 = int(y2 - (y2 - y1) * 0.3)
                plate_region = frame[plate_y1:y2, x1:x2]

                if plate_region.size > 0:
                    # تحسين الصورة
                    thresh = preprocess_for_ocr(plate_region)

                    # قراءة اللوحة
                    result = reader.readtext(thresh, detail=0, paragraph=True)
                    if result:
                        cleaned = re.sub(r'[^A-Z0-9]', '', result[0].upper().replace(' ', ''))

                        if len(cleaned) >= 4:
                            confidence = min(95, 60 + len(cleaned) * 5)
                            plate_width_px = x2 - x1
                            distance = calculate_distance(plate_width_px)

                            plates_found.append({
                                'plate': cleaned,
                                'confidence': confidence,
                                'distance': distance,
                                'box': (x1, y1, x2, y2),
                                'plate_box': (x1, plate_y1, x2, y2)
                            })

                            # رسم على الصورة
                            cv2.rectangle(frame, (x1, y1), (x2, y2), GREEN, 2)
                            cv2.rectangle(frame, (x1, plate_y1), (x2, y2), RED, 2)

                            # كتابة النص
                            font = cv2.FONT_HERSHEY_SIMPLEX
                            distance_text = f"{distance:.2f}m" if distance != float('inf') else "Unknown"

                            cv2.putText(frame, f"Plate: {cleaned}", (x1, y1 - 50),
                                       font, 0.6, YELLOW, 2)
                            cv2.putText(frame, f"Conf: {confidence:.0f}%", (x1, y1 - 25),
                                       font, 0.5, CYAN, 2)
                            cv2.putText(frame, f"Dist: {distance_text}", (x1, y1 - 2),
                                       font, 0.5, WHITE, 2)

    return frame, plates_found

# ============================================
# تشغيل الكاميرا
# ============================================

def start_camera():
    """تشغيل الكاميرا وعرض الفيديو المباشر"""

    # كود JavaScript لفتح الكاميرا في Colab
    js = Javascript('''
        async function startCamera() {
            const div = document.createElement('div');
            document.body.appendChild(div);

            const video = document.createElement('video');
            video.width = 640;
            video.height = 480;
            div.appendChild(video);

            const stream = await navigator.mediaDevices.getUserMedia({video: true});
            video.srcObject = stream;
            await video.play();

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            div.appendChild(canvas);

            const ctx = canvas.getContext('2d');

            // Capture frame function
            window.captureFrame = function() {
                ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
                return canvas.toDataURL('image/jpeg', 0.8);
            };

            // Stop camera function
            window.stopCamera = function() {
                stream.getTracks().forEach(track => track.stop());
                div.remove();
            };

            // Show video
            video.style.display = 'block';
            canvas.style.display = 'none';

            return true;
        }
    ''')

    display(js)
    eval_js('startCamera()')

    print("\n📸 Camera started!")
    print("Press Ctrl+C to stop")
    print("="*60)

    detected_plates = {}
    frame_count = 0

    try:
        while True:
            # التقاط صورة من الكاميرا
            img_data = eval_js('captureFrame()')

            if img_data:
                # تحويل البيانات إلى صورة
                img_data = img_data.split(',')[1]
                img_bytes = b64decode(img_data)
                img_np = np.frombuffer(img_bytes, dtype=np.uint8)
                frame = cv2.imdecode(img_np, cv2.IMREAD_COLOR)

                if frame is not None:
                    frame_count += 1

                    # معالجة كل 5 إطارات
                    if frame_count % 5 == 0:
                        processed_frame, plates = read_plate_from_frame(frame)

                        # عرض النتائج
                        for plate_info in plates:
                            plate = plate_info['plate']
                            confidence = plate_info['confidence']
                            distance = plate_info['distance']

                            if plate not in detected_plates:
                                detected_plates[plate] = {
                                    'count': 0,
                                    'confidence': confidence,
                                    'distance': distance
                                }

                            detected_plates[plate]['count'] += 1

                            distance_text = f"{distance:.2f}m" if distance != float('inf') else "Unknown"
                            print(f"\n✅ Detected: {plate}")
                            print(f"   🎯 Confidence: {confidence:.0f}%")
                            print(f"   📏 Distance: {distance_text}")
                            print(f"   📊 Count: {detected_plates[plate]['count']}")

                    # عرض الفيديو
                    cv2_imshow(frame)

    except KeyboardInterrupt:
        print("\n\n⏹ Stopping camera...")
        eval_js('stopCamera()')

    # النتائج النهائية
    print("\n" + "="*60)
    print("📊 FINAL RESULTS")
    print("="*60)
    print("   🚗 Plate - Count - Confidence - Distance")
    print("-"*60)

    for plate, info in detected_plates.items():
        distance = info.get('distance', float('inf'))
        dist_str = f"{distance:.2f}m" if distance != float('inf') else "Unknown"
        print(f"   🚗 {plate} - {info['count']} times (Conf: {info['confidence']:.0f}%) - Dist: {dist_str}")

# ============================================
# تشغيل الكاميرا
# ============================================

# لازم تستورد numpy
import numpy as np

# دالة لعرض الصور في Colab
from IPython.display import display
from PIL import Image as PILImage

def cv2_imshow(img):
    """عرض صورة OpenCV في Colab"""
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    pil_img = PILImage.fromarray(img_rgb)
    display(pil_img)

# تشغيل الكاميرا
start_camera()