# -*- coding: utf-8 -*-
"""distance and ID with video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fq6cf37DEnnXrlv3Fvl6lmDDgtaRiY4
"""

from google.colab import files
import cv2
import easyocr
import numpy as np
from ultralytics import YOLO
import pandas as pd

print("="*60)
print("🚦 FINAL - Detection + Distance + Plate Reading")
print("="*60)

# 1️⃣ رفع الفيديو
print("\n📤 Upload your video:")
uploaded = files.upload()
video_path = list(uploaded.keys())[0]

# 2️⃣ تحميل النماذج
detector = YOLO('yolov8n.pt')
reader = easyocr.Reader(['en'], gpu=False, verbose=False)

# 3️⃣ إعدادات المسافة
class DistanceCalculator:
    def __init__(self):
        self.car_actual_width = 1.8
        self.focal_length_px = 650
    def calculate(self, width_px):
        if width_px <= 5:
            return None
        return (self.car_actual_width * self.focal_length_px) / width_px

distance_calc = DistanceCalculator()

# 4️⃣ معالجة الفيديو
cap = cv2.VideoCapture(video_path)
fps = int(cap.get(cv2.CAP_PROP_FPS))
frame_count = 0
all_detections = []
unique_plates = set()

print("\n🎥 Processing video...")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    if frame_count % 15 != 0:
        continue

    results = detector(frame, verbose=False)

    for box in results[0].boxes:
        if int(box.cls[0]) == 2 and float(box.conf[0]) > 0.4:
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            # حساب المسافة
            distance = distance_calc.calculate(x2 - x1)
            if not distance or distance > 100:
                continue

            plate_id = None

            # محاولة قراءة اللوحة
            plate_y1 = max(0, int(y2 - (y2-y1)*0.35))
            plate_region = frame[plate_y1:y2, x1:x2]

            if plate_region.size > 0:
                # تكبير وتحسين
                plate_big = cv2.resize(plate_region, (400, 150))
                gray = cv2.cvtColor(plate_big, cv2.COLOR_BGR2GRAY)
                gray = cv2.bilateralFilter(gray, 9, 75, 75)
                _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

                result = reader.readtext(thresh, detail=0, paragraph=True)
                if result:
                    plate_text = result[0].strip().replace(' ', '')
                    plate_text = ''.join(c for c in plate_text if c.isalnum())
                    if len(plate_text) >= 3:
                        plate_id = plate_text
                        unique_plates.add(plate_id)

            # تخزين كل كشف
            all_detections.append({
                'plate_id': plate_id if plate_id else '???',
                'distance_m': round(distance, 1),
                'frame': frame_count,
                'time_sec': round(frame_count / fps, 1),
                'confidence': float(box.conf[0])
            })

            if plate_id:
                print(f"   ✅ Frame {frame_count}: {plate_id} | {distance:.1f}m")
            else:
                print(f"   🚗 Frame {frame_count}: ??? | {distance:.1f}m", end='\r')

cap.release()

# 5️⃣ عرض النتائج
print("\n\n" + "="*60)
print(f"📊 RESULTS: {len(all_detections)} detections, {len(unique_plates)} unique plates")
print("="*60)

if all_detections:
    df = pd.DataFrame(all_detections)
    print(df.to_string(index=False))

    print(f"\n📈 Unique plates found: {unique_plates}")

    # حفظ النتائج
    df.to_csv('all_detections.csv', index=False)
    files.download('all_detections.csv')

    # ملف نصي بسيط
    with open('results.txt', 'w') as f:
        for d in all_detections:
            f.write(f"{d['frame']},{d['plate_id']},{d['distance_m']}m,{d['time_sec']}s\n")
    files.download('results.txt')

print("\n✅ Done!")

from google.colab import files
import cv2
import easyocr
import numpy as np
from ultralytics import YOLO
import pandas as pd

print("="*60)
print("🚦 FINAL - Distance + Plate Reading (All Detections)")
print("="*60)

# 1️⃣ رفع الفيديو
print("\n📤 Upload your video:")
uploaded = files.upload()
video_path = list(uploaded.keys())[0]

# 2️⃣ تحميل النماذج
detector = YOLO('yolov8n.pt')
reader = easyocr.Reader(['en'], gpu=False, verbose=False)

# 3️⃣ إعدادات المسافة
class DistanceCalculator:
    def __init__(self):
        self.car_actual_width = 1.8
        self.focal_length_px = 650
    def calculate(self, width_px):
        if width_px <= 5:
            return None
        return (self.car_actual_width * self.focal_length_px) / width_px

distance_calc = DistanceCalculator()

# 4️⃣ معالجة الفيديو
cap = cv2.VideoCapture(video_path)
fps = int(cap.get(cv2.CAP_PROP_FPS))
frame_count = 0
all_detections = []
unique_plates = set()

def enhance_plate(img):
    """تحسين اللوحة للقراءة"""
    h, w = img.shape[:2]
    img = cv2.resize(img, (w*3, h*3), interpolation=cv2.INTER_CUBIC)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.equalizeHist(gray)
    gray = cv2.bilateralFilter(gray, 9, 75, 75)
    thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2)
    return thresh

print("\n🎥 Processing video...")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    if frame_count % 15 != 0:
        continue

    results = detector(frame, verbose=False)

    for box in results[0].boxes:
        if int(box.cls[0]) == 2 and float(box.conf[0]) > 0.4:
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            # حساب المسافة
            distance = distance_calc.calculate(x2 - x1)
            if not distance or distance > 100:
                continue

            plate_id = None

            # قص اللوحة
            plate_y1 = max(0, int(y2 - (y2-y1)*0.35))
            plate_region = frame[plate_y1:y2, x1:x2]

            if plate_region.size > 0:
                enhanced = enhance_plate(plate_region)
                result = reader.readtext(enhanced, detail=0, paragraph=True)
                if result:
                    plate_text = result[0].strip().replace(' ', '')
                    plate_text = ''.join(c for c in plate_text if c.isalnum())
                    if len(plate_text) >= 3:
                        plate_id = plate_text
                        unique_plates.add(plate_text)

            # تخزين كل كشف (بالمسافة واللوحة لو موجودة)
            all_detections.append({
                'frame': frame_count,
                'plate': plate_id if plate_id else '???',
                'distance_m': round(distance, 1),
                'time_sec': round(frame_count / fps, 1)
            })

            if plate_id:
                print(f"   ✅ Frame {frame_count}: {plate_id} | {distance:.1f}m")
            else:
                print(f"   🚗 Frame {frame_count}: ??? | {distance:.1f}m")

cap.release()

# 5️⃣ عرض النتائج
print("\n" + "="*60)
print(f"📊 RESULTS: {len(all_detections)} detections, {len(unique_plates)} unique plates")
print("="*60)

df = pd.DataFrame(all_detections)
print(df.to_string(index=False))

print(f"\n📈 Unique plates found: {unique_plates}")

# حفظ النتائج
df.to_csv('all_detections.csv', index=False)
files.download('all_detections.csv')

# ملف نصي مرتب
with open('results.txt', 'w') as f:
    f.write("Frame,Plate,Distance(m),Time(s)\n")
    for d in all_detections:
        f.write(f"{d['frame']},{d['plate']},{d['distance_m']},{d['time_sec']}\n")
files.download('results.txt')

print("\n✅ Done!")