# -*- coding: utf-8 -*-
"""distance and ID with camera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175lTEEcO6vEZ6pOKU7x7ZkshSo4QWKbX
"""

!pip install easyocr
!pip install ultralytics

import cv2
import easyocr
import numpy as np
from ultralytics import YOLO
import pandas as pd
import time
from datetime import datetime

print("="*60)
print("🚦 LIVE CAMERA - Distance + Plate Reading")
print("="*60)

# 1️⃣ تحميل النماذج
print("\n📦 Loading models...")
detector = YOLO('yolov8n.pt')
reader = easyocr.Reader(['en'], gpu=False, verbose=False)
print("✅ Models loaded!")

# 2️⃣ إعدادات المسافة
class DistanceCalculator:
    def __init__(self):
        self.car_actual_width = 1.8  # متر
        self.focal_length_px = 650   # هتضبطيه بالمعايرة
    def calculate(self, width_px):
        if width_px <= 5:
            return None
        return (self.car_actual_width * self.focal_length_px) / width_px

distance_calc = DistanceCalculator()

# 3️⃣ فتح الكاميرا
print("\n📷 Opening camera...")
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

if not cap.isOpened():
    print("❌ Cannot open camera!")
    exit()
print("✅ Camera ready!")

# 4️⃣ متغيرات التخزين
all_detections = []
unique_plates = set()
frame_count = 0
process_every = 5  # كل 5 إطارات عشان السرعة

def enhance_plate(img):
    """تحسين اللوحة للقراءة"""
    h, w = img.shape[:2]
    img = cv2.resize(img, (w*3, h*3), interpolation=cv2.INTER_CUBIC)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.equalizeHist(gray)
    gray = cv2.bilateralFilter(gray, 9, 75, 75)
    thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2)
    return thresh

print("\n🎥 Live camera started! Press 'q' to stop")
print("="*60)

try:
    while True:
        ret, frame = cap.read()
        if not ret:
            print("Failed to grab frame")
            break

        frame_count += 1

        # معالجة كل 5 إطارات
        if frame_count % process_every == 0:
            results = detector(frame, verbose=False)

            for box in results[0].boxes:
                if int(box.cls[0]) == 2 and float(box.conf[0]) > 0.4:
                    x1, y1, x2, y2 = map(int, box.xyxy[0])

                    # حساب المسافة
                    distance = distance_calc.calculate(x2 - x1)
                    if not distance or distance > 100:
                        continue

                    plate_id = None

                    # قص اللوحة
                    plate_y1 = max(0, int(y2 - (y2-y1)*0.35))
                    plate_region = frame[plate_y1:y2, x1:x2]

                    if plate_region.size > 0:
                        enhanced = enhance_plate(plate_region)
                        result = reader.readtext(enhanced, detail=0, paragraph=True)
                        if result:
                            plate_text = result[0].strip().replace(' ', '')
                            plate_text = ''.join(c for c in plate_text if c.isalnum())
                            if len(plate_text) >= 3:
                                plate_id = plate_text
                                if plate_id not in unique_plates:
                                    unique_plates.add(plate_id)
                                    print(f"\n   ✅ NEW PLATE: {plate_id} | {distance:.1f}m | Frame {frame_count}")

                    # تخزين الكشف
                    all_detections.append({
                        'frame': frame_count,
                        'plate': plate_id if plate_id else '???',
                        'distance_m': round(distance, 1),
                        'time': datetime.now().strftime("%H:%M:%S")
                    })

                    # رسم المربع على الصورة
                    color = (0, 255, 0) if plate_id else (0, 0, 255)
                    cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
                    cv2.putText(frame, f"{distance:.1f}m", (x1, y1-10),
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
                    if plate_id:
                        cv2.putText(frame, plate_id, (x1, y2+20),
                                   cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 0, 0), 2)

            # عرض معلومات على الشاشة
            cv2.putText(frame, f"Plates found: {len(unique_plates)}", (10, 30),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 255), 2)
            cv2.putText(frame, "Press 'q' to quit", (10, 60),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)

        # عرض الفيديو
        cv2.imshow('Live V2P System', frame)

        # خروج بالضغط على 'q'
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

except KeyboardInterrupt:
    print("\n\n🛑 Stopped by user")

finally:
    # إغلاق الكاميرا
    cap.release()
    cv2.destroyAllWindows()

    # عرض النتائج النهائية
    print("\n" + "="*60)
    print(f"📊 FINAL RESULTS")
    print("="*60)
    print(f"Total frames processed: {frame_count}")
    print(f"Total car detections: {len(all_detections)}")
    print(f"Unique plates found: {len(unique_plates)}")

    if unique_plates:
        print(f"\n📋 Unique plates:")
        for i, plate in enumerate(sorted(unique_plates), 1):
            print(f"   {i}. {plate}")

    # حفظ النتائج
    if all_detections:
        df = pd.DataFrame(all_detections)
        csv_file = f"live_detections_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        df.to_csv(csv_file, index=False)
        print(f"\n💾 Results saved to: {csv_file}")

        # ملف نصي بسيط
        txt_file = f"plates_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        with open(txt_file, 'w') as f:
            f.write(f"Live Camera Session: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("="*50 + "\n")
            f.write(f"Unique plates: {', '.join(sorted(unique_plates))}\n")
            f.write(f"Total detections: {len(all_detections)}\n")

    print("\n✅ Done!")