/**
 ******************************************************************************
 * @file    syscalls.c
 * @author  Auto-generated by STM32CubeIDE
 * @brief   Newlib low-level stubs, plus `printf` retargeting over the ITM.
 * @ingroup system
 *
 * @details
 * Newlib expects a hosted operating system underneath it. There isn't one here,
 * so every POSIX call it might reach for has to be answered by something. This
 * file provides those answers.
 *
 * Two kinds of function live here:
 *
 * - **The one that does real work.** @ref _write is what `printf` ultimately
 *   calls, and it is retargeted onto the Cortex-M4's ITM trace port via
 *   @ref ITM_SendChar. That is what makes `printf` show up in the debugger's SWO
 *   console with no UART involved.
 * - **Everything else.** `_fork`, `_execve`, `_link`, `_unlink` and friends are
 *   stubs that fail politely: they set `errno` and return -1. They exist only so
 *   the linker resolves them; nothing in the firmware calls them.
 *
 * @note The ITM is a Cortex-M3/M4/M7 feature. This file would not work on an
 *       M0/M0+, which has no ITM.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

/////////////////////////////////////////////////////////////////////////////////////////////////////////
//					Implementation of printf like feature using ARM Cortex M3/M4/ ITM functionality
//					This function will not work for ARM Cortex M0/M0+
/////////////////////////////////////////////////////////////////////////////////////////////////////////

//Debug Exception and Monitor Control Register base address
/** @brief Debug Exception and Monitor Control Register — bit 24 (TRCENA) gates all trace, including the ITM. */
#define DEMCR *((volatile uint32_t *)0xE000EDFCU)

/* ITM register addresses */
/** @brief ITM stimulus port 0: writing a byte here emits it on the SWO pin. Bit 0 reads back as "FIFO ready". */
#define ITM_STIMULUS_PORT0 *((volatile uint32_t *)0xE0000000)
/** @brief ITM Trace Enable: one bit per stimulus port; port 0 must be enabled before a write is accepted. */
#define ITM_TRACE_EN *((volatile uint32_t *)0xE0000E00)

/**
 * @brief Emit one character on the ITM stimulus port (the SWO trace pin).
 * @param ch The character to send.
 * @note Busy-waits for the ITM FIFO to drain, so with no debugger attached and
 *       the trace port unclocked this can spin. It is a debug path only — the
 *       ADAS tasks never call `printf`.
 */
void ITM_SendChar(uint8_t ch)
{
  //Enable TRCENA
  DEMCR |= (1 << 24);

  //enable stimulus port 0
  ITM_TRACE_EN |= (1 << 0);

  // read FIFO status in bit [0]:
  while (!(ITM_STIMULUS_PORT0 & 1))
    ;

  //Write to ITM stimulus port0
  ITM_STIMULUS_PORT0 = ch;
}

/* Variables */

/**
 * @brief Character sink for `printf`, overridable by the application.
 * @param ch The character to emit.
 * @return The character written.
 * @note Weak, and not overridden here: @ref _write goes straight to the ITM.
 */
extern int __io_putchar(int ch) __attribute__((weak));

/**
 * @brief Character source for `scanf`, overridable by the application.
 * @return The character read.
 */
extern int __io_getchar(void) __attribute__((weak));

/** @brief Backing store for @ref environ — an empty environment. */
char *__env[1] = { 0 };

/** @brief The process environment Newlib hands to `getenv`; always empty here. */
char **environ = __env;

/* Functions */
/** @brief Semihosting hook Newlib may call; nothing to do without a debug monitor. */
void initialise_monitor_handles()
{
}

/**
 * @brief Process ID of the "current process".
 * @return Always 1 — there is only ever one program on the MCU.
 */
int _getpid(void)
{
  return 1;
}

/**
 * @brief Send a signal to a process. There are no processes, so this always fails.
 * @param pid Ignored.
 * @param sig Ignored.
 * @return -1, with `errno` set to `EINVAL`.
 */
int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

/**
 * @brief Terminate the program.
 * @param status Exit status; passed to @ref _kill and otherwise ignored.
 * @note Does not return — there is nowhere to exit *to*, so it hangs in a loop.
 *       In practice the watchdog then resets the MCU.
 */
void _exit(int status)
{
  _kill(status, -1);
  while (1)
  {
  } /* Make sure we hang here */
}

/**
 * @brief Backend for `scanf` and friends: read @p len characters via `__io_getchar`.
 * @param file Ignored — there is no file system.
 * @param[out] ptr Buffer to fill.
 * @param len Number of characters to read.
 * @return @p len, always: the read is assumed to succeed.
 */
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

/**
 * @brief Backend for `printf`: push @p len characters out over the ITM.
 * @param file Ignored — stdout and stderr both land here.
 * @param[in] ptr Characters to write.
 * @param len How many to write.
 * @return @p len, always.
 */
__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    ITM_SendChar(*ptr++);
  }
  return len;
}

/**
 * @brief Close a file descriptor. There are none.
 * @param file Ignored.
 * @return -1, always.
 */
int _close(int file)
{
  (void)file;
  return -1;
}

/**
 * @brief Report the type of an open file descriptor.
 * @param file Ignored.
 * @param[out] st Receives `S_IFCHR` — every descriptor is a character device.
 * @return 0, always.
 */
int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

/**
 * @brief Is this descriptor a terminal?
 * @param file Ignored.
 * @return 1, always — which is what makes stdout line-buffered rather than block-buffered.
 */
int _isatty(int file)
{
  (void)file;
  return 1;
}

/**
 * @brief Seek within a file. Nothing here is seekable.
 * @param file Ignored.
 * @param ptr Ignored.
 * @param dir Ignored.
 * @return 0, always.
 */
int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

/**
 * @brief Open a file. There is no file system, so this always fails.
 * @param path Ignored.
 * @param flags Ignored.
 * @return -1, always.
 */
int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

/**
 * @brief Wait for a child process. There are no processes.
 * @param status Ignored.
 * @return -1, with `errno` set to `ECHILD`.
 */
int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

/**
 * @brief Delete a file. There is no file system.
 * @param name Ignored.
 * @return -1, with `errno` set to `ENOENT`.
 */
int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

/**
 * @brief Report process CPU times.
 * @param buf Ignored.
 * @return -1, always — the firmware keeps time with the FreeRTOS tick instead.
 */
int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

/**
 * @brief Report the type of a named file.
 * @param file Ignored.
 * @param[out] st Receives `S_IFCHR`.
 * @return 0, always.
 */
int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

/**
 * @brief Create a hard link. There is no file system.
 * @param old Ignored.
 * @param new Ignored.
 * @return -1, with `errno` set to `EMLINK`.
 */
int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

/**
 * @brief Fork a process. There are no processes.
 * @return -1, with `errno` set to `EAGAIN`.
 */
int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

/**
 * @brief Replace the running program. Not possible on bare metal.
 * @param name Ignored.
 * @param argv Ignored.
 * @param env Ignored.
 * @return -1, with `errno` set to `ENOMEM`.
 */
int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
